table Date
	lineageTag: 273d2494-c83a-42d3-8f8c-d72efe7dc7aa
	dataCategory: Time

	column Date
		dataType: dateTime
		isKey
		lineageTag: 1289fba2-c208-4bcb-8a88-089165697419
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Date

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ebc9c1f5-2b8d-469b-9db2-d5edc74705cb
		summarizeBy: none
		sourceColumn: Year

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Year Quarter'
		dataType: string
		lineageTag: 6f2474a9-b9df-40ea-b164-3723ba491ff7
		summarizeBy: none
		sourceColumn: Year Quarter
		sortByColumn: 'Year Quarter Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year Quarter Number'
		dataType: int64
		formatString: 0
		lineageTag: 31b94143-dc0b-452e-9b66-e149dadd60f8
		summarizeBy: none
		sourceColumn: Year Quarter Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Quarter
		dataType: string
		lineageTag: 0fd3b1b9-ed11-4107-a554-70da6f935847
		summarizeBy: none
		sourceColumn: Quarter

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year Month'
		dataType: string
		lineageTag: 84ccc004-8d23-4f1c-aa0c-611d098a6e15
		summarizeBy: none
		sourceColumn: Year Month
		sortByColumn: 'Year Month Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year Month Short'
		dataType: string
		lineageTag: 502d2fc8-1d03-4260-96df-e19b61aa1d06
		summarizeBy: none
		sourceColumn: Year Month Short
		sortByColumn: 'Year Month Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Year Month Number'
		dataType: int64
		formatString: 0
		lineageTag: b38bf0c1-4d78-4df2-a433-f333f686e077
		summarizeBy: none
		sourceColumn: Year Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column Month
		dataType: string
		lineageTag: 794b6de6-e00d-4fc1-b0c1-5489f8d23de9
		summarizeBy: none
		sourceColumn: Month
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Short'
		dataType: string
		lineageTag: 209b2bbc-efc9-466d-ae02-116df0f6298f
		summarizeBy: none
		sourceColumn: Month Short
		sortByColumn: 'Month Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 4bd9b0f8-4db9-45b8-aea3-7b000c4d531f
		summarizeBy: none
		sourceColumn: Month Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Day of Week'
		dataType: string
		lineageTag: 58652893-6a45-4cb5-8bbf-6e9b52cbe9cf
		summarizeBy: none
		sourceColumn: Day of Week
		sortByColumn: 'Day of Week Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Short'
		dataType: string
		lineageTag: 1ae7db73-ecdf-4ae0-a655-d381c4d7e035
		summarizeBy: none
		sourceColumn: Day of Week Short
		sortByColumn: 'Day of Week Number'

		changedProperty = SortByColumn

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Day of Week Number'
		dataType: int64
		formatString: 0
		lineageTag: 63a7504c-1d46-45ab-8e03-375572adfecb
		summarizeBy: none
		sourceColumn: Day of Week Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Working Day'
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 07240336-3d1d-4f4a-88b5-29e956714d6b
		summarizeBy: none
		sourceColumn: Working Day

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Working Day Number'
		dataType: int64
		formatString: 0
		lineageTag: 1c7efc65-d811-4e05-a82b-91cd066191a4
		summarizeBy: none
		sourceColumn: Working Day Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	hierarchy 'Date Year Hierarchy'
		lineageTag: 81d7fbf3-dc96-4316-8013-51796733b75e

		level Year
			lineageTag: 2b95006f-4b1d-4bae-b561-7b9f09ae4ab4
			column: Year

		level Quarter-Year
			lineageTag: 19f37db8-c906-4952-8836-f591834fc1f7
			column: 'Year Quarter'

		level 'Month Year'
			lineageTag: ea13144a-2b7e-4621-9e70-159f52aec4db
			column: 'Year Month Short'

		level Date
			lineageTag: b05ec3eb-259c-43d4-91de-2794b4b413ca
			column: Date

		changedProperty = IsHidden

	hierarchy 'Date Hierarchy'
		lineageTag: ad3807aa-7939-42a9-966e-60107dfc13fd

		level Year
			lineageTag: 0df6a745-bf1e-470f-9d86-824438df7825
			column: Year

		level Quarter
			lineageTag: 66539b8e-5463-46cd-8de7-70372ead2fed
			column: Quarter

		level Month
			lineageTag: 0fdefc73-a3f1-4d1e-958d-6df9df81e8ff
			column: 'Month Short'

		level Date
			lineageTag: 9e0235f0-8c22-4c18-a8a5-bef9da1ad7c9
			column: Date

		changedProperty = IsHidden

	partition Date-44d762f0-a871-4687-b253-096276d9658b = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents(#"Files Path", [ApiVersion=15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    #"Data" = #"Shared Documents"{[Name="Data"]}[Content],
				    #"Contoso Sales" = #"Data"{[Name="Contoso Sales"]}[Content],
				    #"Csv" = #"Contoso Sales"{[Name="Date.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(Csv,[Delimiter=",", Columns=16, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type datetime}, {"Year", Int64.Type}, {"Year Quarter", type text}, {"Year Quarter Number", Int64.Type}, {"Quarter", type text}, {"Year Month", type text}, {"Year Month Short", type text}, {"Year Month Number", Int64.Type}, {"Month", type text}, {"Month Short", type text}, {"Month Number", Int64.Type}, {"Day of Week", type text}, {"Day of Week Short", type text}, {"Day of Week Number", Int64.Type}, {"Working Day", type logical}, {"Working Day Number", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

