table Sales
	lineageTag: 94d3ea3b-4449-4e27-903d-c961f1df5413

	column 'Order Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 91ea6a29-4cac-4426-9100-5736937552bf
		summarizeBy: none
		sourceColumn: Order Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Line Number'
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 45bd733b-90c9-4ecc-93d6-37528e2e27b4
		summarizeBy: none
		sourceColumn: Line Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Order Date'
		dataType: dateTime
		isHidden
		lineageTag: 64b1d016-32bc-4c20-80d7-a5adc3b9ae88
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Delivery Date'
		dataType: dateTime
		isHidden
		lineageTag: fb541e07-fdfb-40c9-9166-29777f049df4
		summarizeBy: none
		sourceColumn: Delivery Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column CustomerKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b35afdc7-615a-4e88-8c36-36c10285f310
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f917bacb-2013-409d-9d94-8b40068bc9a7
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f011ea83-0d14-41e5-a9f2-8d532338586f
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c8ca10d3-f54d-4c5d-b5ef-da854e2d7973
		summarizeBy: none
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column 'Unit Price'
		dataType: decimal
		isHidden
		formatString: € #,##0
		lineageTag: 8c2ee660-1f97-48df-a30b-9e6818ed5be9
		summarizeBy: none
		sourceColumn: Unit Price

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Net Price'
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 690e56a1-1bb6-4aa8-83bc-2b81fa8e4bf7
		summarizeBy: none
		sourceColumn: Net Price

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Unit Cost'
		dataType: decimal
		isHidden
		formatString: € #,##0
		lineageTag: 07c65c15-9e35-47c1-bbab-9cca274818c7
		summarizeBy: none
		sourceColumn: Unit Cost

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column 'Currency Code'
		dataType: string
		isHidden
		lineageTag: af1aa82f-8a7e-4d57-9da8-8d64994488a5
		summarizeBy: none
		sourceColumn: Currency Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Exchange Rate'
		dataType: decimal
		isHidden
		formatString: 0.0000
		lineageTag: 7ddca17e-170a-4c4d-aa29-37f19394e838
		summarizeBy: none
		sourceColumn: Exchange Rate

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	partition Sales-4929449f-be0b-48cf-a44e-c644698415ba = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents(#"Files Path", [ApiVersion=15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    #"Data" = #"Shared Documents"{[Name="Data"]}[Content],
				    #"Contoso Sales" = #"Data"{[Name="Contoso Sales"]}[Content],
				    #"Csv" = #"Contoso Sales"{[Name="Sales.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(Csv,[Delimiter=",", Columns=13, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Order Number", Int64.Type}, {"Line Number", Int64.Type}, {"Order Date", type datetime}, {"Delivery Date", type datetime}, {"CustomerKey", Int64.Type}, {"StoreKey", Int64.Type}, {"ProductKey", Int64.Type}, {"Quantity", Int64.Type}, {"Unit Price", Currency.Type}, {"Net Price", Currency.Type}, {"Unit Cost", Currency.Type}, {"Currency Code", type text}, {"Exchange Rate", Currency.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

