table Store
	lineageTag: aca9499e-9ded-4d0a-835d-f1f04b9d2e92

	column StoreKey
		dataType: int64
		isHidden
		isKey
		formatString: 0
		lineageTag: d808ff79-ebed-42c7-a2cc-e5819db00ac0
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Store Code'
		dataType: int64
		formatString: 0
		lineageTag: 4cbe2709-3503-41b1-bd0a-02060b2181cf
		summarizeBy: none
		sourceColumn: Store Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 81211736-338f-448f-8ba1-c94a9d45cb93
		dataCategory: Country
		summarizeBy: none
		sourceColumn: Country

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: d3331643-69c3-4865-a20e-a88041f23a9c
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: State

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: ab6c5a52-78f2-4d17-9886-d4405c05dedb
		isDefaultLabel
		summarizeBy: none
		sourceColumn: Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Square Meters'
		dataType: int64
		formatString: #,0
		lineageTag: c28257f1-4665-4f2a-820f-af2af0874374
		summarizeBy: none
		sourceColumn: Square Meters

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Open Date'
		dataType: dateTime
		lineageTag: af882c1a-2eb8-4c51-a83e-1e2e1f650443
		summarizeBy: none
		sourceColumn: Open Date

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Close Date'
		dataType: dateTime
		lineageTag: adc3d2bd-b96c-43e3-9ab1-b8ba09ec0857
		summarizeBy: none
		sourceColumn: Close Date

		changedProperty = FormatString

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Status
		dataType: string
		lineageTag: 9d1fa82f-d400-4ef6-a90a-9824c27acd5c
		summarizeBy: none
		sourceColumn: Status

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Status 2' = IF( Store[Status] = "", "Open", Store[Status])
		lineageTag: 3526f8fe-295a-44be-b517-bb7cf58f6c7d
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition Store-4e2fa8b8-517f-4c17-ae5a-7d36051099bc = m
		mode: import
		source =
				let
				    Source = SharePoint.Contents(#"Files Path", [ApiVersion=15]),
				    #"Shared Documents" = Source{[Name="Shared Documents"]}[Content],
				    #"Data" = #"Shared Documents"{[Name="Data"]}[Content],
				    #"Contoso Sales" = #"Data"{[Name="Contoso Sales"]}[Content],
				    #"Csv" = #"Contoso Sales"{[Name="Store.csv"]}[Content],
				    #"Imported CSV" = Csv.Document(Csv,[Delimiter=",", Columns=9, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Imported CSV", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"StoreKey", Int64.Type}, {"Store Code", Int64.Type}, {"Country", type text}, {"State", type text}, {"Name", type text}, {"Square Meters", Int64.Type}, {"Open Date", type datetime}, {"Close Date", type datetime}, {"Status", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

